version: "3.8"

services:
  api-gateway:
    build:
      context: ./api-gateway/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env  
      - ./api-gateway/.env 
    depends_on:
      - redis
      - rabbitmq

  identity-service:
    build:
      context: ./identity-service/
      dockerfile: Dockerfile
    env_file:
      - .env
      - ./identity-service/.env
    depends_on:
      - redis
      - rabbitmq

  post-service:
    build:
      context: ./post-service/
      dockerfile: Dockerfile
    env_file:
      - .env
      - ./post-service/.env
    depends_on:
      - redis
      - rabbitmq

  media-service:
    build:
      context: ./media-service/
      dockerfile: Dockerfile
    env_file:
      - .env
      - ./media-service/.env
    depends_on:
      - redis
      - rabbitmq

  search-service:
    build:
      context: ./search-service/
      dockerfile: Dockerfile
    env_file:
      - .env
      - ./search-service/.env
    depends_on:
      - redis
      - rabbitmq

  redis:
    image: redis:alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    env_file:
      - .env  
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 20s
      retries: 5
    env_file:
      - .env  

volumes:
  redis_data:
